#include "../../includes/httpGen/generateErrorPage.hpp"

std::string generateErrorPage(const std::string& errorMessage)
{
	std::string statusCode = errorMessage.substr(9, 3);
	std::string errorText = errorMessage.substr(13);

	std::string body = "<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
		"<head>\n"
			"<meta charset=\"UTF-8\">\n"
			"<title>Error " + statusCode + "</title>\n"
		"</head>\n"
		"<body>\n"
			"<div class=\"error-container\">\n"
				"<h1>" + statusCode + "</h1>\n"
				"<p>" + errorText + "</p>\n"
			"</div>\n"
		"</body>\n"
		"<style>\n"
			"body {\n"
				"display: flex;\n"
				"flex-direction: column;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
				"height: 100vh;\n"
				"font-family: Arial, sans-serif;\n"
				"margin: 0;\n"
				"padding: 20px;\n"
			"}\n"
			"h1 {\n"
				"font-size: 5rem;\n"
				"font-weight: bold;\n"
				"color: #002ed2;\n"
				"line-height: 1.3;\n"
				"margin: 0;\n"
				"text-align: center;\n"
			"}\n"
			"p {\n"
				"font-size: 2rem;\n"
				"color: #666;\n"
				"margin: 0;\n"
				"line-height: 1.3;\n"
				"text-align: center;\n"
			"}\n"
		"</style>\n"
	"</html>\n"
	;
	return (body);
}
